version: '3.8'

services:
  fbm-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      # If not provided, `MONGO_URI` defaults to `mongodb://localhost:27017`
      - MONGO_URI=mongodb://fbm-mongo:27017
    labels:
      - traefik.enable=true
      - traefik.http.routers.fbm-api.rule=Host(`fastapi-beanie-mongodb.aguest.me`)
      - traefik.http.routers.fbm-api.tls=true
      - traefik.http.routers.fbm-api.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - traefik
    command: gunicorn
    depends_on:
      - fbm-mongo

  fbm-mongo:
    image: mongo:6-jammy
    networks:
      - traefik
    volumes:
      - fbm-data:/data/db

volumes:
  fbm-data:

networks:
  traefik: